services:
  - type: web
    name: grind-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py seed
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: "true"