# Generated by Django 5.2.12 on 2026-09-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
